---
# The name of the section to be used in the OpenStack clouds.yaml config file.
os_cloud: test

# Name prefix used for all the entities created in the OpenStack cluster.
os_prefix: hurrosprod

# The name of the configured SSH key.
os_key_name: "{{ os_prefix }} SSH Key"

# The key material written to the registered SSH key.
os_public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"