---
- name: create keys directory
  file: path=../keys state=directory mode=0755

- name: create SSH host key for master
  command: >
      ssh-keygen -N '' -t rsa -b 2048 -f ../keys/master_host
      -C "master@{{ os_prefix }}"
  args:
    creates: ../keys/master_host

- name: create SSH host key for workers
  command: >
      ssh-keygen -N '' -t rsa -b 2048 -f ../keys/worker_host
      -C "worker@{{ os_prefix }}"
  args:
    creates: ../keys/worker_host
