---
- name: install chromium using dnf
  when: ansible_pkg_mgr == 'dnf'
  become: true
  become_user: root
  dnf: name=chromium state=present

- name: install chromium using apt
  when: ansible_pkg_mgr == 'apt'
  become: true
  become_user: root
  apt: name=chromium state=present